baseURL = 'https://jamespatrickhiggins.com'
languageCode = 'en-us'
title = 'James Patrick Higgins (1949–2025)'

disableKinds = ["taxonomy", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[menu]
[[menu.main]]
  name = 'James P. Higgins'
  url = '/'
  weight = '10'
[[menu.main]]
  name = 'Photo gallery'
  url = '/gallery'
  weight = '20'
[[menu.main]]
  name = 'Tributes'
  url = '/tributes'
  weight = '30'
